version: '3'
services:
    web:
        build: .
        ports:
        - "80:5000"
        volumes:
            - .:/app
        command: flask run
        environment:
          - DATABASE_URL=postgres://postgres:yourmom@psql:5432/postgres
          - MONGODB_URI=mongodb://mongo:27017/mongodb
        stdin_open: true
        tty: true
    psql:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=yourmom
    mongo:
        image: mongo:latest
